export const QUERY_KEY = {
  ABOUT_US: "ABOUT_US",
  SERVICE: "SERVICE",
  ABOUT_MEMBER: "ABOUT_MEMBER",
  PRICE_PLAN: "PRICE_PLAN",
  MORE_SERVICES: "MORE_SERVICES",
  NEWS: "NEWS",
  DEPARTMENT_HEALTH: "DEPARTMENT_HEALTH",
};
