export const API_URL = {
  ABOUT_US: "home",
  SERVICE: "service",
  ABOUT_MEMBER: "home",
  PRICE_PLAN: "our-plants",
  MORE_SERVICES: "home",
  NEWS: "home",
  DEPARTMENT_HEALTH: "departments",
  LOGIN: "auth/login",
  CREATE_STAFF: "staffs",
  CREATE_MANAGER: "admin/manager",
  CREATE_REQUEST: "requests",
  CREATE_WORKSPACE: "admin/workspace",
  LIST_WORKSPACE: "admin/workspace",
  WORKSPACE_DETAIL: "admin/workspace",
  CREATE_WORKSPACE_DETAIL: "admin/workspace",
  UNASSIGN_USERS: "unassign-user",
  ADDASSIGN_USERS: "assign-user",
  GETALL_USERS: "users",
  REQUESTS: "requests",
  APPROVE_REQUEST: "requests/approve",
};
